# Generated by Django 5.2.8 on 2025-11-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Lega')),
                ('country', models.CharField(max_length=50, verbose_name='Paese')),
                ('tier', models.IntegerField(default=1, verbose_name='Livello (1=Serie A, 2=B...)')),
            ],
            options={
                'verbose_name': 'Campionato',
                'verbose_name_plural': 'Campionati',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Data e Ora')),
                ('round_number', models.IntegerField(help_text='Utile per calcolare stanchezza stagionale', verbose_name='Giornata')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmata'), ('FINISHED', 'Terminata'), ('POSTPONED', 'Rinviata'), ('LIVE', 'In Corso')], default='SCHEDULED', max_length=20)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Match',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: RandomForest_v1', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Squadra')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
                ('stadium_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stadium_capacity', models.IntegerField(blank=True, null=True)),
                ('pitch_type', models.CharField(choices=[('GRASS', 'Erba'), ('SYNTHETIC', 'Sintetico'), ('HYBRID', 'Ibrido')], default='GRASS', max_length=20, verbose_name='Tipo Campo')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Squadra',
                'verbose_name_plural': 'Squadre',
            },
        ),
        migrations.CreateModel(
            name='DynamicFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Es: RAIN_INTENSITY', max_length=50, verbose_name='Nome Fattore')),
                ('value', models.CharField(help_text='Es: High', max_length=255, verbose_name='Valore')),
                ('source', models.CharField(blank=True, help_text='Es: WeatherAPI', max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_factors', to='predictors.match')),
            ],
            options={
                'verbose_name': 'Fattore Dinamico',
                'verbose_name_plural': 'Fattori Dinamici',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('winner', models.CharField(choices=[('1', 'Home'), ('X', 'Draw'), ('2', 'Away')], max_length=1)),
                ('home_stats', models.JSONField(blank=True, default=dict, verbose_name='Stats Casa (JSON)')),
                ('away_stats', models.JSONField(blank=True, default=dict, verbose_name='Stats Ospite (JSON)')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='predictors.match')),
            ],
            options={
                'verbose_name': 'Risultato Match',
                'verbose_name_plural': 'Risultati Match',
            },
        ),
        migrations.CreateModel(
            name='OddsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=50)),
                ('opening_1', models.FloatField()),
                ('opening_X', models.FloatField()),
                ('opening_2', models.FloatField()),
                ('closing_1', models.FloatField()),
                ('closing_X', models.FloatField()),
                ('closing_2', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='predictors.match')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quote',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prob_home', models.FloatField()),
                ('prob_draw', models.FloatField()),
                ('prob_away', models.FloatField()),
                ('predicted_winner', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('confidence_score', models.FloatField(help_text='Confidenza del modello 0-100')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictors.match')),
                ('model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictors.modelregistry')),
            ],
            options={
                'verbose_name': 'Previsione IA',
                'verbose_name_plural': 'Previsioni IA',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField(verbose_name='Anno Inizio')),
                ('year_end', models.IntegerField(verbose_name='Anno Fine')),
                ('is_current', models.BooleanField(default=False, verbose_name='Stagione Corrente')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='predictors.league')),
            ],
            options={
                'verbose_name': 'Stagione',
                'verbose_name_plural': 'Stagioni',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='predictors.season'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='predictors.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='predictors.team'),
        ),
        migrations.CreateModel(
            name='TeamFormSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_5_matches_points', models.IntegerField(help_text='Punti nelle ultime 5 partite')),
                ('rest_days', models.IntegerField(help_text="Giorni di riposo dall'ultima partita")),
                ('elo_rating', models.FloatField(default=1500.0, help_text='Rating ELO al momento del match')),
                ('injured_count', models.IntegerField(default=0, verbose_name='Num. Infortunati')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_snapshots', to='predictors.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.team')),
            ],
            options={
                'verbose_name': 'Snapshot Forma',
                'verbose_name_plural': 'Snapshot Forma',
                'unique_together': {('match', 'team')},
            },
        ),
    ]
