# Generated by Django 5.2.8 on 2025-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformsnapshot',
            name='avg_goals_conceded_last_5',
            field=models.FloatField(default=0.0, verbose_name='Media Goal subiti (ultime 5)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='avg_goals_scored_last_5',
            field=models.FloatField(default=0.0, verbose_name='Media Goal fatti (ultime 5)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='avg_xg_last_5',
            field=models.FloatField(default=0.0, verbose_name='Media xG fatti (ultime 5)'),
        ),
    ]
