# Generated by Django 5.2.8 on 2025-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0003_alter_prediction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Stemma Squadra'),
        ),
    ]
