# Generated by Django 5.2.8 on 2025-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0004_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformsnapshot',
            name='form_sequence',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Sequenza Forma'),
        ),
    ]
