# Generated by Django 5.2.8 on 2025-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0005_teamformsnapshot_form_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformsnapshot',
            name='efficiency_attack_last_5',
            field=models.FloatField(default=0.0, verbose_name='Efficienza Attacco (Goal - xG)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='efficiency_defense_last_5',
            field=models.FloatField(default=0.0, verbose_name='Efficienza Difesa (xG Subiti - Goal Subiti)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='goal_volatility_last_5',
            field=models.FloatField(default=0.0, verbose_name='Volatilità Goal (Deviazione Std)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='xg_ratio_last_5',
            field=models.FloatField(default=0.5, verbose_name='xG Ratio Dominio'),
        ),
    ]
