# Generated by Django 5.2.8 on 2025-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0006_teamformsnapshot_efficiency_attack_last_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformsnapshot',
            name='is_derby',
            field=models.BooleanField(default=False, verbose_name='Derby / Rivalità'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='pressure_index',
            field=models.FloatField(default=0.0, verbose_name='Indice Pressione (0-100)'),
        ),
    ]
