# Generated by Django 5.2.8 on 2025-12-02 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_teamformsnapshot_is_derby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='market_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valore Rosa (mln €)'),
        ),
        migrations.CreateModel(
            name='Rivalry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(default=10, help_text='Intensità della rivalità da 1 a 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Nome Derby')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_1', to='predictors.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_2', to='predictors.team')),
            ],
            options={
                'verbose_name': 'Rivalità / Derby',
                'verbose_name_plural': 'Rivalità / Derby',
                'unique_together': {('team1', 'team2')},
            },
        ),
    ]
