# Generated by Django 5.2.8 on 2025-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0008_team_market_value_rivalry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamformsnapshot',
            name='is_derby',
            field=models.IntegerField(default=0, verbose_name='Intensità Derby (0-10)'),
        ),
    ]
