# Generated by Django 5.2.8 on 2025-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0009_alter_teamformsnapshot_is_derby'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_confidence_score', models.IntegerField(default=60, verbose_name='Punteggio Minimo Confidenza')),
                ('slip_min_score', models.IntegerField(default=70, verbose_name='Punteggio Minimo Schedina')),
                ('slip_size', models.IntegerField(default=4, verbose_name='Num. Eventi Schedina')),
                ('win_threshold', models.FloatField(default=0.6, verbose_name='Soglia Goal per Vittoria (0.6)')),
                ('draw_threshold', models.FloatField(default=0.3, verbose_name='Soglia Goal per Pareggio (0.3)')),
                ('market_config', models.JSONField(default=dict, help_text='Definisce volatilità, margini e gap per ogni statistica.', verbose_name='Configurazione Mercati (JSON)')),
            ],
            options={
                'verbose_name': 'Configurazione Betting',
                'verbose_name_plural': 'Configurazione Betting',
            },
        ),
    ]
