# Generated by Django 5.2.8 on 2025-12-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0011_seed_betting_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('understat_id', models.CharField(max_length=50, unique=True, verbose_name='ID Understat')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='predictors.team', verbose_name='Squadra Attuale')),
            ],
            options={
                'verbose_name': 'Giocatore',
                'verbose_name_plural': 'Giocatori',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, verbose_name='Posizione')),
                ('is_starter', models.BooleanField(default=False, verbose_name='Titolare')),
                ('minutes', models.IntegerField(default=0, verbose_name='Minuti')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('xg', models.FloatField(default=0.0, verbose_name='xG')),
                ('xa', models.FloatField(default=0.0, verbose_name='xA')),
                ('xg_chain', models.FloatField(default=0.0, verbose_name='xG Chain')),
                ('xg_buildup', models.FloatField(default=0.0, verbose_name='xG Buildup')),
                ('rating', models.FloatField(default=6.0, verbose_name='Voto')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='predictors.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='predictors.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.team')),
            ],
            options={
                'verbose_name': 'Statistica Giocatore (Match)',
                'verbose_name_plural': 'Statistiche Giocatori (Match)',
                'unique_together': {('player', 'match')},
            },
        ),
    ]
