# Generated by Django 5.2.8 on 2025-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0012_player_playermatchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamformsnapshot',
            name='key_players_impact_score',
            field=models.FloatField(default=1.0, verbose_name='Impatto Giocatori Chiave (0-1)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='starters_avg_rating_last_5',
            field=models.FloatField(default=6.0, verbose_name='Media Voto Titolari (last 5)'),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='starters_avg_xg_last_5',
            field=models.FloatField(default=0.0, verbose_name='Media xG Titolari (last 5)'),
        ),
    ]
