# Generated by Django 5.2.8 on 2025-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0014_prediction_away_possession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ruolo Principale'),
        ),
    ]
