# Generated by Django 5.2.8 on 2025-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0015_player_primary_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='expected_return',
            field=models.DateField(blank=True, null=True, verbose_name='Rientro Previsto'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponibile'), ('INJURED', 'Infortunato'), ('SUSPENDED', 'Squalificato')], default='AVAILABLE', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='clean_sheet',
            field=models.BooleanField(default=False, verbose_name='Clean Sheet'),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='Gol Subiti'),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='saves',
            field=models.IntegerField(default=0, verbose_name='Parate'),
        ),
    ]
