# Generated by Django 5.2.8 on 2025-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0016_player_expected_return_player_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddsmovement',
            name='provider',
            field=models.CharField(default='Manual', help_text='Fonte dati (es. TheOddsAPI)', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='api_name',
            field=models.CharField(blank=True, help_text='Nome usato da TheOddsAPI per il mapping', max_length=100, null=True, verbose_name='Nome API (TheOdds)'),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='closing_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='closing_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='closing_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='opening_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='opening_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oddsmovement',
            name='opening_X',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
