# Generated by Django 5.2.8 on 2025-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0017_oddsmovement_provider_team_api_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('Goal', 'Goal'), ('Shots', 'Tiri Totali'), ('ShotsOT', 'Tiri in Porta'), ('Corners', 'Corner'), ('Cards', 'Cartellini'), ('Fouls', 'Falli'), ('Offsides', 'Fuorigioco'), ('1X2', 'Esito Finale')], max_length=20)),
                ('market_type', models.CharField(choices=[('OVER', 'Over / Casa'), ('UNDER', 'Under / Ospite'), ('1', 'Vittoria Casa (1X2)'), ('X', 'Pareggio (1X2)'), ('2', 'Vittoria Ospite (1X2)')], max_length=10)),
                ('accuracy', models.FloatField(default=50.0, help_text='Percentuale di successo storica (0-100)')),
                ('sample_size', models.IntegerField(default=0, help_text='Numero di match analizzati')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profilo Accuratezza',
                'verbose_name_plural': 'Profili Accuratezza',
                'unique_together': {('stat_type', 'market_type')},
            },
        ),
    ]
