# Generated by Django 5.2.8 on 2025-12-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0018_accuracyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.IntegerField(default=50, verbose_name='Velocità')),
                ('physicality', models.IntegerField(default=50, verbose_name='Fisicità')),
                ('stamina', models.IntegerField(default=50, verbose_name='Resistenza')),
                ('shooting', models.IntegerField(default=50, verbose_name='Tiro')),
                ('passing', models.IntegerField(default=50, verbose_name='Passaggio')),
                ('dribbling', models.IntegerField(default=50, verbose_name='Dribbling')),
                ('defending', models.IntegerField(default=50, verbose_name='Difesa')),
                ('experience', models.IntegerField(default=50, verbose_name='Esperienza')),
                ('positioning', models.IntegerField(default=50, verbose_name='Posizionamento')),
                ('tactical_role', models.CharField(blank=True, max_length=50, verbose_name='Ruolo Tattico')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='predictors.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROBABLE', 'Probabile'), ('OFFICIAL', 'Ufficiale')], default='PROBABLE', max_length=20)),
                ('formation', models.CharField(default='4-4-2', max_length=10)),
                ('starting_xi', models.JSONField(default=list, verbose_name='Titolari (IDs)')),
                ('bench', models.JSONField(blank=True, default=list, verbose_name='Panchina (IDs)')),
                ('source', models.CharField(blank=True, help_text='Fonte (es. Football-Data, Sky, Algoritmo)', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='predictors.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.team')),
            ],
            options={
                'verbose_name': 'Formazione Pre-Match',
                'verbose_name_plural': 'Formazioni Pre-Match',
                'unique_together': {('match', 'team')},
            },
        ),
    ]
