# Generated by Django 5.2.8 on 2025-12-05 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0019_playerattributes_matchlineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INJURY', 'Infortunio'), ('SUSPENSION', 'Squalifica'), ('OTHER', 'Altro')], default='INJURY', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Dettaglio (es. Lesione muscolare)')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='predictors.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.team')),
            ],
            options={
                'verbose_name': 'Assenza Match',
                'verbose_name_plural': 'Assenze Match',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
