# Generated by Django 5.2.8 on 2025-12-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0020_matchabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Arbitro')),
                ('matches_count', models.IntegerField(default=0, verbose_name='Partite Arbitrate')),
                ('yellow_cards_avg', models.FloatField(default=0.0, verbose_name='Media Gialli')),
                ('red_cards_avg', models.FloatField(default=0.0, verbose_name='Media Rossi')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arbitro',
                'verbose_name_plural': 'Arbitri',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='predictors.referee', verbose_name='Arbitro'),
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(blank=True, default=0, null=True)),
                ('penalties', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(default=999)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictors.team')),
            ],
            options={
                'verbose_name': 'Capocannoniere',
                'verbose_name_plural': 'Capocannonieri',
                'ordering': ['rank', '-goals'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
